### ISSUE TITLE
group-data variants aren't part of UnoCSS or this preset

### ISSUE THREAD

**Issue by john-prutton** [fisand/unocss-preset-shadcn#1]
Components like the `NavigationMenu` component from Shadcn-ui uses `.group` in conjunction with `data-state=open` and children like the `NavigationMenuTrigger` component uses `group-data-[state=open]`. 

This is not possible with the current `unocss-preset-shadcn` or default UnoCSS installation. I made a demo of a group-data variant over on [unocss/issues/2827](https://github.com/unocss/unocss/issues/2827#issuecomment-1620209750) which is working for my specific case and links important files showcasing how Tailwind implements this functionality. 

If I find the time, I will bullet-proof this code so it complies with [Tailwind's tests](https://github.com/tailwindlabs/tailwindcss/pull/9559/commits/ad82dadb0c78f77d557626792047f2ae76196da1) and make a PR for this repo.

Here is what I have so far:
```js
// uno.config.ts

import { defineConfig } from 'unocss'

export default defineConfig({
  variants: [
  // group-data-[...]:
  (matcher) => {
    const regexResult = matcher.match(/group-(data-\[[^ ]*\]):([^ ]*)/)
    if (!regexResult) return matcher

    const data = regexResult[1].replaceAll(/[\[\]]/g, "")
    const classname = regexResult[2]
    
    return {
      matcher: classname,
      selector: s => `.group[${data}] ${s}`,
    }
  }
],
})
```

**Comment by zouhangwithsweet** [comment]
Great help :). I will check it as soon as possible.
